name: portariafrontend
description: Frontend Flutter para o desafio de controle de portaria.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Pacotes essenciais
  http: ^0.13.6

  # Cupertino icons para iOS (opcional, mas padrão)
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
